global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true
  # Used to define custom react.fullname in template.
  projectName: "react"
  # image sets the repo,tag and pullPolicy of the project
  image:
    repository: "nginx"
    tag: latest
    pullPolicy: Always

  # Namespace where release will be deployed
  namespace: "react"

frontend:
  # True if you want to enable api deployment.
  enabled: true

  # Defines the path where gunicorn serves the application 
  # command: npm run start

  replicaCount: 1
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
  
  # Used to define custom readinessProbe settings (ping TCP port defined in service)
  readinessProbe:
    enabled: false
    
  # extraEnvironmentVars is a list of extra enviroment variables to set with the stateful set. These could be
  # used to include variables required for auto-unseal.
  extraEnvironmentVars: 
    # GOOGLE_PROJECT: myproject

  # extraSecretEnvironmentVars is a list of extra enviroment variables to set with the stateful set.
  # These variables take value from existing Secret objects.
  extraSecretEnvironmentVars: []
    # - envName: AWS_SECRET_ACCESS_KEY
    #   secretName: project
    #   secretKey: AWS_SECRET_ACCESS_KEY
  
  # Affinity Settings for api pods
  # This should be a multi-line string matching the affinity section of a
  # PodSpec.
  affinity: null

  # Toleration Settings for api pods
  # This should be a multi-line string matching the Toleration array
  # in a PodSpec.
  tolerations: null

  # nodeSelector labels for server pod assignment, formatted as a muli-line string.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  # Example:
  # nodeSelector: |
  #   environment: qa
  nodeSelector: {}

  terminationGracePeriodSeconds: 300
    
  ingress:
    enabled: false
    labels: {}
      # traffic: external
    annotations: {}
    hosts:
      - host: frontend.demo.io
        paths:
          - /

    tls:
      enabled: true

  # Enables a headless service to be used by
  service:
    enabled: true

    # Port on which Backoffice server is listening
    port: 3000
    # Target port to which the service should be mapped to
    targetPort: 3000