apiVersion: skaffold/v2beta29
kind: Config
# requires:
#   - configs: [configHelm]
metadata:
  name: configArgoPlugin
deploy:
  kubectl:  
    manifests:
      - argocd/config/plugin.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: configHelm
deploy:
  helm:
    releases:
      # ArgoCD
      - name: argocd
        remoteChart: argo-cd
        repo: https://argoproj.github.io/argo-helm
        namespace: argocd
        version: 5.37.0
        createNamespace: true
        valuesFiles:
          - "./argocd/config/values.yaml"
        upgradeOnChange: false
      # ChartMuseum
      # - name: chartmuseum
      #   remoteChart: chartmuseum
      #   repo: https://chartmuseum.github.io/charts
      #   namespace: chartmuseum
      #   version: 3.10.1
      #   createNamespace: true
      #   valuesFiles:
      #     - "./chartmuseum/values.yaml"
      #   upgradeOnChange: false
---
apiVersion: skaffold/v2beta29
kind: Config
requires:
  - configs: [configHelm]
metadata:
  name: configArgoApplication
deploy:
  kubectl:  
    manifests:
      - argocd/applications/stable-envs/*