apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-plugin-cfg
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-plugin
    spec:
      version: v1.0
      init:
        command: ["/bin/sh", "-c"]
        args: ['if [ "$ARGOCD_ENV_ADD_HELM_REPOSITORY" = "true" ];then helm repo add $ARGOCD_ENV_CHART_REPOSITORY $ARGOCD_ENV_CHART_REPOSITORY_URL;fi;helm repo update']
      generate:
        command: ["/bin/sh", "-c"]
        args: ['helm template $ARGOCD_ENV_PROJECT_NAME $ARGOCD_ENV_CHART_REPOSITORY/$ARGOCD_ENV_CHART_NAME --include-crds --values $ARGOCD_ENV_VALUES --version $ARGOCD_ENV_CHART_VERSION --set global.namespace=$ARGOCD_APP_NAMESPACE']
      discover:
        fileName: "*values.yaml"

