{{- if .Values.s3.enabled }}
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ .Values.s3.name }}-{{ $.Release.Name }}
spec:
  forProvider:
    policyArnRef:
      name: {{ .Values.s3.name }}-{{ $.Release.Name }}
    roleRef:
      name: {{ .Values.s3.name }}-{{ $.Release.Name }}
{{- end }}