apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ .Values.s3.name }}
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "s3:ListBucket",
                    "s3:GetBucketLocation"
                ],
                "Resource": [
                    "arn:aws:s3:::{{ .Values.s3.name }}"
                ]
            },
            {
                "Effect": "Allow",
                "Action": [
                    "s3:GetObject",
                    "s3:PutObject",
                    "s3:DeleteObject",
                    "s3:GetObjectVersion",
                    "s3:GetObjectTagging",
                    "s3:PutObjectTagging"
                ],
                "Resource": [
                    "arn:aws:s3:::{{ .Values.s3.name }}/*"
                ]
            }
            ]
        }
