{{- if .Values.s3.enabled }}
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.s3.name }}
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: default
{{- end }}