{{- if .Values.s3.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.accountId }}:role/{{ .Values.s3.name }}
  name: {{ .Values.s3.name }}
  namespace: {{ .Values.global.namespace }}
{{- end }}