apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-frontend
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: app-frontend
  project: default
  revisionHistoryLimit: 10
  source:
    path: argocd/applications/values
    plugin:
      env:
      - name: USE_OCI
        value: "false"
      - name: VALUES
        value: "frontend-values.yaml"
      - name: CHART_VERSION
        value: 0.0.1
      - name: CHART_REPOSITORY_URL
        value: http://chartmuseum.chartmuseum.svc.cluster.local
      - name: CHART_REPOSITORY
        value: nerdearla
      - name: CHART_NAME
        value: frontend
      - name: PROJECT_NAME
        value: app-backend
    repoURL: https://github.com/craftech-inc/nerdearla-2023-dynamic-environments.git
    targetRevision: chore_argocd-configuration
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
