{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "django.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "django.fullname" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "django.fullname" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/name: {{ template "django.fullname" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: api
    spec:
      {{ template "api.affinity" . }}
      {{ template "api.tolerations" . }}
      {{ template "api.nodeselector" . }}
      {{ template "api.hostAliases" . }}
      terminationGracePeriodSeconds: {{ .Values.api.terminationGracePeriodSeconds | default 300 }}
      containers:
        - name: django
          image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: {{ .Values.api.command | default "python manage.py runserver 0.0.0.0:8000" }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          {{ template "api.resources" . }}
          {{- if .Values.api.varsSecretName }}
          envFrom:
          - secretRef:
              name: {{ .Values.api.varsSecretName }}
          {{- end }}
          env:
          {{- include "api.extraEnvironmentVars" .Values.api | nindent 10 }}
          {{- include "api.extraSecretEnvironmentVars" .Values.api | nindent 10 }}
         {{ template "api.mounts" . }}
         {{ template "api.volumes" . }}
{{- end }}