{{- if and .Values.api.enabled .Values.api.ingress.enabled -}}
{{- $serviceName := include "django.fullname" . -}}
{{- $servicePort := .Values.api.service.port -}}

{{- $alb := true }}
{{- if not .Values.api.ingress.ingressClassName }}
{{- $alb = false }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "django.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "django.fullname" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.api.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- template "api.ingress.annotations" . }}
spec:
  {{- if $alb }}
  ingressClassName: {{ .Values.api.ingress.ingressClassName | quote }}
  {{- end }}
{{- if .Values.api.ingress.tls }}
  tls:
  {{- range .Values.api.ingress.tls.hosts }}
    - hosts:
        - {{ . | quote }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range $key, $val := (.paths | default (list "/")) }}
          - path: {{ $val.path }}
            pathType: {{ $val.pathType | default "Prefix" }}
            backend:
              service:
              {{- if $val.serviceName }}
                name: {{ $val.serviceName }}
              {{- else }}
                name: {{ $serviceName }}-api-svc
              {{- end }}
                port: 
                  number: {{ $val.servicePort }}
          {{- end}}
        {{- end }}
  {{- end }}
