apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-backend-dynamic-envs
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: craftech-inc
        # The Github repository
        repo: nerdearla-2023-dynamic-environments
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'app-backend-pr-{{number}}'
    spec:
      project: "default"
      destination:
        name: in-cluster
        namespace: app-backend-pr-{{number}}
      source:
        path: argocd/applications/values
        plugin:
          env:
          - name: ADD_HELM_REPOSITORY
            value: "false"
          - name: VALUES
            value: "backend-values.yaml"
          - name: CHART_VERSION
            value: 0.0.2
          - name: CHART_REPOSITORY_URL
            value: http://chartmuseum.chartmuseum.svc.cluster.local:8080
          - name: CHART_REPOSITORY
            value: nerdearla
          - name: CHART_NAME
            value: backend-demo
          - name: PROJECT_NAME
            value: app-backend-pr-{{number}}
        repoURL: https://github.com/craftech-inc/nerdearla-2023-dynamic-environments.git
        targetRevision: chore_argocd-configuration
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true